### PR TITLE
Added Ranges

### PR DESCRIPTION
**Pull request by farooqkz**
!quran command has two form:
`!quran <surah_number> <ayah_number> <lang>`
`!quran <surah_number> <start_ayah_number>-<end_ayah_number> <lang>`
If there is any problem post it here.

### CODE REVIEW

**Comment by farooqkz** [comment]
Maximum difference between start and stop is 5, i may fix this by using sopybot's more

**Comment by farooghkz** [comment]
to see this working, on IRC ping me(pm or just calling my name).

**Comment by farooqkz** [comment]
to see this working, you may ping me on freenode.

**Comment by farooghkz** [comment]
to see this working, on IRC ping me(pm or just calling my name).

**Pull request merged**
